# swagger.yml

openapi: 3.0.0
info:
  title: "Crepery REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    User:
      type: "object"
      required:
        - lastName
        - firstName
        - email
        - personId
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        personId:
          type: "string"
  parameters:
    personId:
      name: "personId"
      description: "personId the user to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /user:
    get:
      operationId: "user.get_all"
      tags:
        - "User"
      summary: "Get the list of Users"
      responses:
        "200":
          description: "Successfully read users list"
    post:
      operationId: "user.create"
      tags:
        - "User"
      summary: "Create a user"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "user"
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: "User Successfully created"

  /user/{personId}:
    get:
      operationId: "user.get"
      tags:
        - User
      summary: "Get one user"
      parameters:
        - $ref: "#/components/parameters/personId"
      responses:
        "200":
          description: "Successfully retrieved user"

    put:
      tags:
        - User
      operationId: "user.update"
      summary: "Update a user"
      parameters:
        - $ref: "#/components/parameters/personId"
      responses:
        "200":
          description: "Successfully updated user"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "user"
              $ref: "#/components/schemas/User"

    delete:
      tags:
        - User
      operationId: "user.delete"
      summary: "Delete a user"
      parameters:
        - $ref: "#/components/parameters/personId"
      responses:
        "204":
          description: "Successfully deleted user"
